export const NAV_ITEMS = [
  ['dashboard', '⌂', 'Dashboard'],
  ['route', '⌁', 'Ruta'],
  ['story', '◆', 'Historia'],
  ['strangers', '✦', 'Forasteros'],
  ['camp', '⌂', 'Campamento'],
  ['requests', '✉', 'Encargos'],
  ['map', '⌖', 'Mapa'],
  ['animals', '♞', 'Animales'],
  ['legendary', '★', 'Legendarios'],
  ['fish', '≈', 'Peces'],
  ['plants', '♧', 'Plantas'],
  ['horses', '♘', 'Caballos'],
  ['weapons', '†', 'Armas'],
  ['equipment', '◈', 'Equipo'],
  ['cards', '▥', 'Cromos'],
  ['outfits', '♜', 'Atuendos'],
  ['satchels', '▣', 'Zurrones'],
  ['saddles', '♢', 'Sillas'],
  ['camp_upgrades', '⌂', 'Mejoras camp.'],
  ['challenges', 'Ⅹ', 'Desafíos'],
  ['collectibles', '▦', 'Coleccionables'],
  ['points', '⌖', 'Puntos interés'],
  ['encounters', '⚡', 'Encuentros'],
  ['secrets', '?', 'Secretos'],
  ['documents', '▤', 'Docs. y únicos'],
  ['crafting', '⚒', 'Crafteo'],
  ['archive', '▤', 'Archivo'],
  ['achievements', '♛', 'Logros'],
] as const;

export type AppView = (typeof NAV_ITEMS)[number][0];
