'use client';

import { useState } from 'react';
import { buildRecipeState } from '@/features/crafting/model';
import { useProgress } from '@/features/progress/progress-context';
import type { CanonicalCatalog } from '@/lib/catalog/types';

export function CraftingView({ catalog }: { catalog: CanonicalCatalog }) {
  const progress = useProgress();
  const [selectedId, setSelectedId] = useState(catalog.recipes[0]?.id ?? '');
  const selected = catalog.recipes.find((recipe) => recipe.id === selectedId) ?? catalog.recipes[0];
  const entity = selected ? catalog.entities.find((item) => item.id === selected.entityId) : null;
  const criteria = entity ? catalog.criteria.filter((item) => item.entityId === entity.id) : [];
  const recipeState = selected ? buildRecipeState(selected, criteria, progress.snapshot) : null;
  return <section className="content-view"><header className="view-heading"><div><small>MATERIALES ≠ OBJETO FABRICADO</small><h1>Crafteo y mejoras</h1><p>Inventario y fabricación se guardan por separado. Tener cuatro pieles de jabalí no hace que Pearson trabaje por telepatía.</p></div><span className="big-count">{catalog.recipes.length}</span></header><div className="split-browser"><div className="browser-panel"><div className="entity-grid crafting-grid">{catalog.recipes.map((recipe) => { const e = catalog.entities.find((item) => item.id === recipe.entityId); return <button key={recipe.id} className={`entity-card ${selected?.id === recipe.id ? 'selected' : ''}`} onClick={() => setSelectedId(recipe.id)}><div><small>{e?.category ?? 'receta'}</small><h3>{e?.name ?? recipe.id}</h3></div><span>{recipe.requirements.length}</span></button>; })}</div></div><aside className="detail-panel">{selected && entity ? <><small className="detail-kicker">RECETA CANÓNICA</small><h2>{entity.name}</h2>{recipeState && <div className={`craft-readiness ${recipeState.materialsReady ? 'ready' : ''}`}><small>{recipeState.materialsReady ? 'MATERIALES PREPARADOS' : 'FALTAN MATERIALES'}</small><b>{recipeState.materialsReady ? (recipeState.crafted ? 'Fabricado' : 'Listo para fabricar') : `${recipeState.requirements.reduce((sum, req) => sum + req.missing, 0)} unidades pendientes`}</b><p>{recipeState.materialsReady && !recipeState.crafted ? 'Tener los materiales no marca el objeto como fabricado. Ese check sigue siendo independiente.' : 'Inventario y fabricación mantienen estados separados.'}</p></div>}<h4>Materiales necesarios</h4><div className="material-list">{selected.requirements.map((req, index) => { const material = req.materialId ? catalog.entities.find((item) => item.id === req.materialId) : null; const id = req.materialId ?? `unknown:${index}`; const have = progress.snapshot.inventory[id] ?? 0; return <div className={`material-row ${have >= req.quantity ? 'ready' : ''}`} key={`${id}:${index}`}><div><b>{material?.name ?? req.materialName ?? 'Material'}</b><small>Necesitas {req.quantity}{req.tier ? ` · ${req.tier}` : ''}</small></div><div className="qty"><button onClick={() => progress.setInventoryQuantity(id, Math.max(0, have - 1))}>−</button><strong>{have}</strong><button onClick={() => progress.setInventoryQuantity(id, have + 1)}>+</button></div></div>; })}</div><h4>Estado de fabricación</h4><div className="criteria-list">{criteria.map((criterion) => { const done = progress.snapshot.criteria[criterion.id] === 'completed'; return <button key={criterion.id} className={done ? 'done' : ''} onClick={() => progress.setCriterionStatus(criterion.id, done ? 'not_started' : 'completed')}><span>{done ? '✓' : ''}</span><div><b>{criterion.label}</b><small>{criterion.key}</small></div></button>; })}</div></> : null}</aside></div></section>;
}
