// Spanish display names for the RDR2 animal compendium. Canonical English names remain the keys.
export const ANIMAL_ES: Record<string, string> = {
  'Alligator Snapping Turtle': 'Tortuga caimán',
  'Alpine Goat': 'Cabra alpina',
  'American Alligator': 'Caimán americano',
  'American Allitgator (Small)': 'Caimán americano (pequeño)',
  'American Badger': 'Tejón americano',
  'American Bison': 'Bisonte americano',
  'American Black Bear': 'Oso negro americano',
  'American Bullfrog': 'Rana toro americana',
  'American Crow': 'Cuervo americano',
  'American Domestic Cat': 'Gato doméstico americano',
  'American Fox Hound': 'Foxhound americano',
  'American Gray Fox': 'Zorro gris americano',
  'American Muskrat': 'Rata almizclera americana',
  'American Pronghorn Buck': 'Berrendo americano macho',
  'American Pronghorn Doe': 'Berrendo americano hembra',
  'American Red Fox': 'Zorro rojo americano',
  'American Red Squirrel': 'Ardilla roja americana',
  'American Robin': 'Petirrojo americano',
  'American Tree Sparrow': 'Gorrión arborícola americano',
  'American White Pelican': 'Pelícano blanco americano',
  'Angus Bull': 'Toro Angus',
  'Angus Ox': 'Buey Angus',
  'Australian Shepherd': 'Pastor australiano',
  'Baja California Pronghorn Buck': 'Berrendo de Baja California macho',
  'Baja California Pronghorn Doe': 'Berrendo de Baja California hembra',
  'Bald Eagle': 'Águila calva',
  'Baltimore Oriole': 'Oropéndola de Baltimore',
  'Band-Tailed Pigeon': 'Paloma de cola bandeada',
  'Banded Gila Monster': 'Monstruo de Gila bandeado',
  'Berkshire Pig': 'Cerdo Berkshire',
  'Big China Pig': 'Cerdo chino grande',
  'Black Rat': 'Rata negra',
  'Black Squirrel': 'Ardilla negra',
  'Black-Tailed Jackrabbit': 'Liebre de cola negra',
  'Black-Tailed Rattlesnake': 'Serpiente de cascabel de cola negra',
  'Bloodhound': 'Sabueso',
  'Blue Jay': 'Arrendajo azul',
  'Blue & Yellow Macaw': 'Guacamayo azul y amarillo',
  'Bluetick Coonhound': 'Sabueso Bluetick',
  'Border Collie': 'Border collie',
  'Brown Pelican': 'Pelícano pardo',
  'Brown Rat': 'Rata parda',
  'California Quail': 'Codorniz de California',
  'California Valley Coyote': 'Coyote del valle de California',
  'Californian Condor': 'Cóndor de California',
  'Californian Horned Owl': 'Búho cornudo de California',
  'Canada Goose': 'Ganso de Canadá',
  'Carolina Parakeet': 'Periquito de Carolina',
  'Catahoula Cur': 'Perro leopardo de Catahoula',
  'Cedar Waxwing': 'Ampelis americano',
  'Chesapeake Bay Retriever': 'Retriever de Chesapeake',
  'Chinese Ring-Necked Pheasant': 'Faisán chino de collar',
  'Coastal Horned Owl': 'Búho cornudo costero',
  'Collared Peccary': 'Pecarí de collar',
  'Common Loon': 'Colimbo común',
  'Cottonmouth Snake': 'Serpiente boca de algodón',
  'Cougar': 'Puma',
  'Cuban Land Crab': 'Cangrejo terrestre cubano',
  'Desert Bighorn Ram': 'Carnero muflón del desierto',
  'Desert Bighorn Sheep': 'Oveja muflón del desierto',
  'Desert Iguana': 'Iguana del desierto',
  'Devon Bull': 'Toro Devon',
  'Devon Ox': 'Buey Devon',
  'Diamondback Rattlesnake': 'Serpiente de cascabel diamantino',
  'Dominique Chicken': 'Gallina Dominique',
  'Dominique Rooster': 'Gallo Dominique',
  'Double-Crested Cormorant': 'Cormorán de doble cresta',
  'Eastern Turkey Vulture': 'Buitre pavo oriental',
  'Eastern Wild Turkey': 'Pavo salvaje oriental',
  'Eurasian Tree Sparrow': 'Gorrión molinero euroasiático',
  'Fer-de-Lance Snake': 'Serpiente terciopelo',
  'Ferruginous Hawk': 'Halcón herrumbroso',
  'Florida Cracker Cow': 'Vaca Florida Cracker',
  'Florida Panther': 'Pantera de Florida',
  'Golden Crowned Sparrow': 'Gorrión coronado dorado',
  'Golden Eagle': 'Águila real',
  'Gray Wolf': 'Lobo gris',
  'Great Blue Heron': 'Garza azulada grande',
  'Great Green Macaw': 'Gran guacamayo verde',
  'Great Horned Owl': 'Gran búho cornudo',
  'Greater Prairie Chicken': 'Gallo de las praderas grande',
  'Green Iguana': 'Iguana verde',
  'Grizzly Bear': 'Oso pardo',
  'Hereford Bull': 'Toro Hereford',
  'Herring Gull': 'Gaviota argéntea',
  'Hooded Oriole': 'Oropéndola encapuchada',
  'Java Chicken': 'Gallina de Java',
  'Java Rooster': 'Gallo de Java',
  'Labrador Retriever': 'Labrador retriever',
  'Laughing Gull': 'Gaviota reidora',
  'Legendary Beaver': 'Castor legendario',
  'Legendary Bharati Grizzly Bear': 'Osa parda legendaria Bharati',
  'Legendary Big Horn Ram': 'Carnero muflón legendario',
  'Legendary Boar': 'Jabalí legendario',
  'Legendary Buck': 'Ciervo macho legendario',
  'Legendary Bull Gator': 'Caimán gigante legendario',
  'Legendary Cougar': 'Puma legendario',
  'Legendary Coyote': 'Coyote legendario',
  'Legendary Elk': 'Uapití legendario',
  'Legendary Fox': 'Zorro legendario',
  'Legendary Giaguaro Panther': 'Pantera legendaria Giaguaro',
  'Legendary Moose': 'Alce legendario',
  'Legendary Pronghorn': 'Berrendo legendario',
  'Legendary Tatanka Bison': 'Bisonte legendario Tatanka',
  'Legendary White Bison': 'Bisonte blanco legendario',
  'Legendary Wolf': 'Lobo legendario',
  'Leghorn Chicken': 'Gallina Leghorn',
  'Leghorn Rooster': 'Gallo Leghorn',
  'Little Brown Bat': 'Pequeño murciélago café',
  'Little Egret': 'Garceta pequeña',
  'Mallard Duck': 'Ánade real',
  'Merino Sheep': 'Oveja merina',
  'Midland Water Snake': 'Serpiente de agua de Midland',
  'Mule': 'Mula',
  'Mutt': 'Chucho',
  'Neotropic Cormorant': 'Cormorán neotropical',
  'Nine-Banded Armadillo': 'Armadillo de nueve bandas',
  'North American Beaver': 'Castor norteamericano',
  'North American Raccoon': 'Mapache norteamericano',
  'Northern Cardinal': 'Cardenal rojo',
  'Northern Copperhead Snake': 'Serpiente cabeza de cobre del norte',
  'Northern Water Snake': 'Serpiente de agua del norte',
  'Old Spot Pig': 'Cerdo Old Spot',
  'Pacific Loon': 'Colimbo del Pacífico',
  'Panther': 'Pantera',
  'Pekin Duck': 'Pato Pekín',
  'Pileated Woodpecker': 'Pájaro carpintero crestado',
  'Poodle': 'Caniche',
  'Rainbow Boa Snake': 'Boa arcoíris',
  'Red-Bellied Woodpecker': 'Pájaro carpintero de vientre rojo',
  'Red Boa Snake': 'Boa roja',
  'Red-Footed Booby': 'Alcatraz de patas rojas',
  'Red Swamp Crayfish': 'Cangrejo de río rojo',
  'Red-Tailed Hawk': 'Halcón de cola roja',
  'Reddish Egret': 'Garceta rojiza',
  'Ring-Billed Gull': 'Gaviota de pico anillado',
  'Ring-Necked Pheasant': 'Faisán de collar',
  'Rio Grande Wild Turkey': 'Pavo salvaje de Río Grande',
  'Rock Pigeon': 'Paloma bravía',
  'Rocky Mountain Bighorn Ram': 'Carnero muflón de las Montañas Rocosas',
  'Rocky Mountain Bighorn Sheep': 'Oveja muflón de las Montañas Rocosas',
  'Rocky Mountain Bull Elk': 'Uapití macho de las Montañas Rocosas',
  'Rocky Mountain Cow Elk': 'Uapití hembra de las Montañas Rocosas',
  'Roseate Spoonbill': 'Espátula rosada',
  'Rough-Legged Hawk': 'Halcón de patas ásperas',
  'Rufus': 'Rufus',
  'Sandhill Crane': 'Grulla canadiense',
  'Scarlet Macaw': 'Guacamayo escarlata',
  'Scarlet Tanager Songbird': 'Piranga escarlata',
  'Siberian Husky': 'Husky siberiano',
  'Sierra Nevada Bighorn Ram': 'Carnero muflón de Sierra Nevada',
  'Sierra Nevada Bighorn Sheep': 'Oveja muflón de Sierra Nevada',
  'Silver Fox': 'Zorro plateado',
  'Snowy Egret': 'Garceta nívea',
  'Sonoran Desert Toad': 'Sapo del desierto de Sonora',
  'Sonoran Pronghorn Buck': 'Berrendo de Sonora macho',
  'Sonoran Pronghorn Doe': 'Berrendo de Sonora hembra',
  'Southern Copperhead Snake': 'Serpiente cabeza de cobre del sur',
  'Standard Donkey': 'Burro estándar',
  'Striped Skunk': 'Mofeta rayada',
  'Sunglow Boa Snake': 'Boa sunglow',
  'Timber Rattlesnake': 'Serpiente de cascabel del bosque',
  'Timber Wolf': 'Lobo de bosque',
  'Tricolored Heron': 'Garza tricolor',
  'Virginia Opossum': 'Zarigüeya de Virginia',
  'Western Bull Moose': 'Alce macho occidental',
  'Western Chipmunk': 'Ardilla listada occidental',
  'Western Gray Squirrel': 'Ardilla gris occidental',
  'Western Moose': 'Alce occidental',
  'Western Raven': 'Cuervo grande occidental',
  'Western Tanager Songbird': 'Piranga occidental',
  'Western Toad': 'Sapo occidental',
  'Western Turkey Vulture': 'Buitre pavo occidental',
  'Whitetail Buck': 'Ciervo macho de cola blanca',
  'Whitetail Deer': 'Ciervo de cola blanca',
  'Whooping Crane': 'Grulla trompetera',
  'Wild Boar': 'Jabalí salvaje',
  'Yellow-Billed Loon': 'Colimbo de pico amarillo',
};
