import { ANIMAL_ES } from './animals-es.ts';

const FISH_ES: Record<string, string> = {
  'Bluegill': 'Pez sol',
  'Bullhead Catfish': 'Bagre cabeza de toro',
  'Chain Pickerel': 'Lucio cadena',
  'Channel Catfish': 'Bagre americano',
  'Lake Sturgeon': 'Esturión de lago',
  'Largemouth Bass': 'Perca americana',
  'Longnose Gar': 'Pejelagarto narigudo',
  'Muskie': 'Muskallonga americano',
  'Northern Pike': 'Lucio europeo',
  'Perch': 'Perca',
  'Redfin Pickerel': 'Lucio americano de aleta roja',
  'Rock Bass': 'Lubina de roca',
  'Smallmouth Bass': 'Lubina de boca pequeña',
  'Sockeye Salmon': 'Salmón rojo',
  'Steelhead Trout': 'Trucha de cabeza de acero',
};

for (const [english, spanish] of Object.entries({ ...FISH_ES })) {
  FISH_ES[`Legendary ${english}`] = `${spanish} legendari${/a$/.test(spanish) ? 'a' : 'o'}`;
}

// Preserve the in-game conventional gender for these labels.
Object.assign(FISH_ES, {
  'Legendary Largemouth Bass': 'Perca americana legendaria',
  'Legendary Perch': 'Perca legendaria',
  'Legendary Rock Bass': 'Lubina de roca legendaria',
  'Legendary Smallmouth Bass': 'Lubina de boca pequeña legendaria',
  'Legendary Steelhead Trout': 'Trucha de cabeza de acero legendaria',
});

const PLANT_ES: Record<string, string> = {
  "Acuna's Star Orchid": 'Orquídea estrella de Acuña',
  'Alaskan Ginseng': 'Ginseng de Alaska',
  'American Ginseng': 'Ginseng americano',
  'Bay Bolete': 'Boleto bayo',
  'Black Currant': 'Grosella negra',
  'Blackberry': 'Zarzamora',
  'Burdock Root': 'Raíz de bardana',
  'Chanterelles': 'Rebozuelos',
  'Cigar Orchid': 'Orquídea cigarro',
  'Clamshell Orchid': 'Orquídea concha de almeja',
  'Common Bulrush': 'Espadaña común',
  'Creeping Thyme': 'Tomillo rastrero',
  'Desert Sage': 'Salvia del desierto',
  "Dragon's Mouth Orchid": 'Orquídea boca de dragón',
  'English Mace': 'Macis inglés',
  'Evergreen Huckleberry': 'Arándano perenne',
  'Ghost Orchid': 'Orquídea fantasma',
  'Golden Currant': 'Grosella dorada',
  'Hummingbird Sage': 'Salvia de colibrí',
  'Indian Tobacco': 'Tabaco indio',
  'Lady of the Night Orchid': 'Orquídea dama de la noche',
  'Lady Slipper Orchid': 'Orquídea zapatilla de dama',
  'Milkweed': 'Asclepia',
  'Moccasin Flower Orchid': 'Orquídea flor de mocasín',
  'Night Scented Orchid': 'Orquídea nocturna',
  'Oleander Sage': 'Adelfa',
  'Oregano': 'Orégano',
  'Parasol Mushroom': 'Seta parasol',
  'Prairie Poppy': 'Amapola de las praderas',
  "Queen's Orchid": 'Orquídea reina',
  "Ram's Head": 'Cabeza de carnero',
  'Rat Tail Orchid': 'Orquídea cola de rata',
  'Red Raspberry': 'Frambuesa roja',
  'Red Sage': 'Salvia roja',
  "Sparrow's Egg Orchid": 'Orquídea huevo de gorrión',
  'Spider Orchid': 'Orquídea araña',
  'Vanilla Flower': 'Flor de vainilla',
  'Violet Snowdrops': 'Campanilla violeta',
  'Wild Carrot': 'Zanahoria silvestre',
  'Wild Feverfew': 'Matricaria silvestre',
  'Wild Mint': 'Menta silvestre',
  'Wintergreen Berry': 'Baya de gaulteria',
  'Yarrow': 'Milenrama',
};

const HORSE_BREED_ES: Record<string, string> = {
  'American Paint': 'Paint americano',
  'American Standardbred': 'American Standardbred',
  'Andalusian': 'Andaluz',
  'Appalooosa': 'Appaloosa',
  'Arabian': 'Árabe',
  'Ardennes': 'Ardenés',
  'Belgian Draft': 'Caballo de tiro belga',
  'Dutch Warmblood': 'Warmblood holandés',
  'Hungarian Halfbred': 'Halfbred húngaro',
  'Kentucky Saddler': 'Saddler de Kentucky',
  'Missouri Fox Trotter': 'Fox Trotter de Misuri',
  'Morgan': 'Morgan',
  'Mustang': 'Mustang',
  'Nokota': 'Nokota',
  'Shire': 'Shire',
  'Suffolk Punch': 'Suffolk Punch',
  'Tennessee Walker': 'Tennessee Walker',
  'Thoroughbred': 'Purasangre',
  'Turkoman': 'Turcomano',
};

const COAT_ES: Record<string, string> = {
  'Grey Overo': 'Overo gris',
  'Overo': 'Overo',
  'Splashed White': 'Blanco salpicado',
  'Tobiano': 'Tobiano',
  'Black': 'Negro',
  'Buckskin': 'Bayo',
  'Palomino Dapple': 'Palomino moteado',
  'Silvertail Buckskin': 'Bayo cola plateada',
  'Dark Bay': 'Castaño oscuro',
  'Perlino': 'Perlino',
  'Rose Grey': 'Tordo rosado',
  'Blanket': 'Manta',
  'Brown Leopard': 'Leopardo marrón',
  'Few Spotted': 'Pocas manchas',
  'Leopard Blanket': 'Manta leopardo',
  'Leopard': 'Leopardo',
  'Chestnut': 'Alazán',
  'Rose Grey Bay': 'Castaño gris rosado',
  'Warped Brindle': 'Atigrado deformado',
  'White': 'Blanco',
  'Bay Roan': 'Ruano castaño',
  'Strawberry Roan': 'Ruano fresa',
  'Blonde Chestnut': 'Alazán rubio',
  'Mealy Chestnut': 'Alazán harinoso',
  'Chocolate Roan': 'Ruano chocolate',
  'Cremello Gold': 'Cremello dorado',
  'Seal Brown': 'Marrón oscuro',
  'Sooty Buckskin': 'Bayo tiznado',
  'Dapple Dark Grey': 'Gris oscuro moteado',
  'Flaxen Chestnut': 'Alazán de crin clara',
  'Piebald Tobiano': 'Tobiano pío',
  'Buttermilk Bucksin': 'Bayo claro',
  'Chestnut Pinto': 'Pinto alazán',
  'Grey': 'Gris',
  'Silver Bay': 'Castaño plateado',
  'Amber Champagne': 'Champán ámbar',
  'Silver Dapple Pinto': 'Pinto plateado moteado',
  'Bay': 'Castaño',
  'Liver Chestnut': 'Alazán hígado',
  'Palomino': 'Palomino',
  'Grullo Dun': 'Grullo dun',
  'Tiger Striped Bay': 'Castaño rayado atigrado',
  'Wild Bay': 'Castaño salvaje',
  'Blue Roan': 'Ruano azul',
  'Reverse Dapple Roan': 'Ruano moteado inverso',
  'White Roan': 'Ruano blanco',
  'Light Grey': 'Gris claro',
  'Raven Black': 'Negro azabache',
  'Red Chestnut': 'Alazán rojo',
  'Sorrel': 'Alazán claro',
  'Black Rabicano': 'Rabicano negro',
  'Dapple Bay': 'Castaño moteado',
  'Flaxen Roan': 'Ruano de crin clara',
  'Gold Palomino': 'Palomino dorado',
  'Mahogany Bay': 'Castaño caoba',
  'Red Roan': 'Ruano rojo',
  'Blood Bay': 'Castaño sangre',
  'Brindle': 'Atigrado',
  'Dapple Grey': 'Gris moteado',
  'Gold': 'Dorado',
  'Silver': 'Plateado',
};

const HORSE_COAT_ES: Record<string, string> = {};
for (const [breed, spanishBreed] of Object.entries(HORSE_BREED_ES)) {
  for (const [coat, spanishCoat] of Object.entries(COAT_ES)) {
    HORSE_COAT_ES[`${breed} · ${coat}`] = `${spanishBreed} · ${spanishCoat}`;
  }
}

const WEAPON_ES: Record<string, string> = {
  "Algernon's Revolver": 'Revólver de Algernon',
  'Ancient Tomahawk': 'Tomahawk antiguo',
  'Antler Knife': 'Cuchillo de asta',
  'Bolt Action Rifle': 'Fusil de cerrojo',
  'Broken Pirate Sword': 'Espada pirata rota',
  "Calloway's Revolver": 'Revólver de Calloway',
  'Carbine Repeater': 'Carabina de repetición',
  'Carcano Rifle': 'Fusil Carcano',
  'Cattleman Revolver': 'Revólver Cattleman',
  'Civil War Knife': 'Cuchillo de la Guerra de Secesión',
  'Cleaver': 'Cuchillo de carnicero',
  'Double-Action Revolver': 'Revólver de doble acción',
  'Double-Barreled Shotgun': 'Escopeta de dos cañones',
  'Double Bit Hatchet': 'Hachuela de doble filo',
  'Dynamite': 'Dinamita',
  'Evans Repeater': 'Evans de repetición',
  'Fire Bottle': 'Botella incendiaria',
  "Flaco's Revolver": 'Revólver de Flaco',
  "Granger's Revolver": 'Revólver de Granger',
  'Hatchet': 'Hachuela',
  'Hewing Hatchet': 'Hachuela de desbaste',
  'High Roller Revolver': 'Revólver de gran apostador',
  'Homing Tomahawk': 'Tomahawk dirigido',
  'Hunter Hatchet': 'Hachuela de cazador',
  'Hunting Knife': 'Cuchillo de caza',
  'Improved Throwing Knife': 'Cuchillo arrojadizo mejorado',
  'Improved Tomahawk': 'Tomahawk mejorado',
  'Jawbone Knife': 'Cuchillo de mandíbula',
  "John's Cattleman Revolver": 'Revólver Cattleman de John',
  "John's Knife": 'Cuchillo de John',
  'Lancaster Repeater': 'Lancaster de repetición',
  'LeMat Revolver': 'Revólver LeMat',
  'Litchfield Repeater': 'Litchfield de repetición',
  'M1899 Pistol': 'Pistola M1899',
  'Machete': 'Machete',
  'Mauser Pistol': 'Pistola Mauser',
  "Micah's Revolver": 'Revólver de Micah',
  "Midnight's Pistol": 'Pistola de Midnight',
  'Ornate Dagger': 'Daga con adornos',
  "Otis Miller's Revolver": 'Revólver de Otis Miller',
  'Poison Throwing Knife': 'Cuchillo arrojadizo envenenado',
  'Pump-Action Shotgun': 'Escopeta de corredera',
  'Rare Rolling Block Rifle': 'Fusil Rolling Block exótico',
  'Rare Shotgun': 'Escopeta exótica',
  'Repeating Shotgun': 'Escopeta de repetición',
  'Rolling Block Rifle': 'Fusil Rolling Block',
  'Rusted Double Bit Hatchet': 'Hachuela de doble filo oxidada',
  'Rusted Hunter Hatchet': 'Hachuela de cazador oxidada',
  'Sawed-Off Shotgun': 'Escopeta recortada',
  'Schofield Revolver': 'Revólver Schofield',
  'Semi-Auto Shotgun': 'Escopeta semiautomática',
  'Semi-Automatic Pistol': 'Pistola semiautomática',
  'Springfield Rifle': 'Fusil Springfield',
  'Throwing Knife': 'Cuchillo arrojadizo',
  'Tomahawk': 'Tomahawk',
  'Varmint Rifle': 'Fusil Varmint',
  'Viking Hatchet': 'Hachuela vikinga',
  'Volatie Dynamite': 'Dinamita inestable',
  'Volatile Fire Bottle': 'Botella incendiaria inestable',
  'Volcanic Pistol': 'Pistola Volcanic',
  'WEAPONS': 'Armas',
  'Wide-Blade Knife': 'Cuchillo de hoja ancha',
};

const EQUIPMENT_ES: Record<string, string> = {
  'Binoculars': 'Prismáticos',
  'Camera': 'Cámara',
  'Electric Lantern': 'Farol eléctrico',
  'Fishing Rod': 'Caña de pescar',
  'Lantern': 'Farol',
  'Lasso': 'Lazo',
  'Off-Hand Holster': 'Funda secundaria',
  'Upgraded Bandolier': 'Bandolera mejorada',
  'Upgraded Gun Belt': 'Cinturón de pistolero mejorado',
  'Upgraded Hoster': 'Funda mejorada',
  'EQUIPMENT': 'Equipo',
};

const CHALLENGE_ES: Record<string, string> = {
  'Bandit': 'Bandido', 'Explorer': 'Explorador', 'Gambler': 'Apostador', 'Herbalist': 'Herborista',
  'Horseman': 'Jinete', 'Master Hunter': 'Maestro cazador', 'Sharpshooter': 'Tirador',
  'Survivalist': 'Superviviente', 'Weapons Expert': 'Experto en armas',
};
for (const [challenge, spanish] of Object.entries(CHALLENGE_ES)) {
  EQUIPMENT_ES[`${challenge} Bandolier`] = `Bandolera de ${spanish.toLowerCase()}`;
  EQUIPMENT_ES[`${challenge} Gun Belt`] = `Cinturón de pistolero de ${spanish.toLowerCase()}`;
  EQUIPMENT_ES[`${challenge} Holster`] = `Funda de ${spanish.toLowerCase()}`;
  EQUIPMENT_ES[`${challenge} Hoster`] = `Funda de ${spanish.toLowerCase()}`;
  EQUIPMENT_ES[`${challenge} Off-Hand Holster`] = `Funda secundaria de ${spanish.toLowerCase()}`;
}

Object.assign(EQUIPMENT_ES, {
  'Alligator Tooth Talisman': 'Talismán de diente de caimán',
  'Bear Claw Talisman': 'Talismán de garra de oso',
  'Beaver Tooth Trinket': 'Abalorio de diente de castor',
  'Bison Horn Talisman': 'Talismán de cuerno de bisonte',
  'Boar Tusk Talisman': 'Talismán de colmillo de jabalí',
  'Buck Antler Trinket': 'Abalorio de asta de ciervo macho',
  'Cat Eye Trinket': 'Abalorio de ojo de gato',
  'Cougar Fang Trinket': 'Abalorio de colmillo de puma',
  'Coyote Fang Trinket': 'Abalorio de colmillo de coyote',
  'Crow Beak Trinket': 'Abalorio de pico de cuervo',
  'Elk Antler Trinket': 'Abalorio de asta de uapití',
  'Fox Claw Trinket': 'Abalorio de garra de zorro',
  'Hawk Talon Trinket': 'Abalorio de garra de halcón',
  "Lion's Paw Trinket": 'Abalorio de pata de león',
  'Moose Antler Trinket': 'Abalorio de asta de alce',
  'Owl Feather Trinket': 'Abalorio de pluma de búho',
  "Panther's Eye Trinket": 'Abalorio de ojo de pantera',
  'Pronghorn Horn Trinket': 'Abalorio de cuerno de berrendo',
  'Ram Horn Trinket': 'Abalorio de cuerno de carnero',
  'Raven Claw Talisman': 'Talismán de garra de cuervo grande',
  'Shark Tooth Trinket': 'Abalorio de diente de tiburón',
  'Tatanka Bison Horn Trinket': 'Abalorio de cuerno de bisonte Tatanka',
  'Turtle Shell Trinket': 'Abalorio de caparazón de tortuga',
  'Wolf Heart Trinket': 'Abalorio de corazón de lobo',
});

export const COMPENDIUM_ES: Record<string, string> = {
  ...ANIMAL_ES,
  ...FISH_ES,
  ...PLANT_ES,
  ...HORSE_BREED_ES,
  ...HORSE_COAT_ES,
  ...WEAPON_ES,
  ...EQUIPMENT_ES,
};
